### ISSUE TITLE
bug: Triton 2.0 makes attention kernel crash

### ISSUE THREAD

**Issue by pommedeterresautee** [ELS-RD/kernl#314]
### Description

Attention doesn't work with new Triton 2.0.
PyTorch 2.0 relies on Triton 2.0
related to https://github.com/openai/triton/issues/1273

### Steps to reproduce

pytest test/test_attention.py 
raises compilation error

### Expected Behavior

no error

### Actual Behavior

dead lock

### Your environment

- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
- Python version (e.g. Python 3.8.10):
- Python package manager (e.g. pip 21.1.2):
- etc.

### Self-service

- [X] I would be willing to help fix this bug myself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pommedeterresautee** [comment]
fixed by #307
